server: 
  port: 11001
  
spring:  h2: 
    console: 
      enabled: true 
      path: /h2-console 
      
    profiles: 
      active: 
      - default 
    data: 
      rest: 
        base-path: /
        
    datasource: 
      url: jdbc:h2:mem:kmooc;MVCC=TRUE
      driverClassName: org.h2.Driver
      username: sa
      password: 
      
    jpa: 
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create-drop